### ISSUE TITLE
Password support

### ISSUE THREAD

**Issue by Hass1000** [noaione/unrar2-cffi#3]
Is it possible for passwords to be supported too?

**Comment by noaione** [comment]
Some of the recent commit should support password, still need to fix some test and will publish it soon

**Comment by noaione** [comment]
A bit late, but see [`v0.4.0`](https://github.com/noaione/unrar2-cffi/releases/tag/v0.4.0)

`pip install -U unrar2-cffi==0.4.0`

Same API format as `ZipFile`.

```py
from unrar.cffi import rarfile

rar = rarfile.RarFile("protected.rar", pwd="password")
```
